// eslint-disable-next-line simple-import-sort/imports
const categories = [
  "Education",
  "Guidance",
  "Career Development",
  "College Tour",
  "Admission",
  "Internships",
  "Scholarships",
  "SoftSkills",
  "Career Planning",
  "Other",
];

const languages = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "he", name: "Hebrew", nativeName: "עברית", flag: "🇮🇱" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", flag: "🇫🇮" },
  { code: "da", name: "Danish", nativeName: "Dansk", flag: "🇩🇰" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴" },
  { code: "cs", name: "Czech", nativeName: "Čeština", flag: "🇨🇿" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", flag: "🇭🇺" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "tl", name: "Filipino", nativeName: "Filipino", flag: "🇵🇭" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ab", name: "Abkhaz", nativeName: "аҧсуа", flag: "🏳️" },
  { code: "aa", name: "Afar", nativeName: "Afaraf", flag: "🏳️" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", flag: "🇿🇦" },
  { code: "ak", name: "Akan", nativeName: "Akan", flag: "🇬🇭" },
  { code: "sq", name: "Albanian", nativeName: "Shqip", flag: "🇦🇱" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", flag: "🇪🇹" },
  { code: "an", name: "Aragonese", nativeName: "Aragonés", flag: "🇪🇸" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", flag: "🇦🇲" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া", flag: "🇮🇳" },
  { code: "av", name: "Avaric", nativeName: "авар мацӀ, магӀарул мацӀ", flag: "🏳️" },
  { code: "ae", name: "Avestan", nativeName: "avesta", flag: "🏳️" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycanca / آذربايجان", flag: "🇦🇿" },
  { code: "bm", name: "Bambara", nativeName: "Bamanankan", flag: "🇲🇱" },
  { code: "ba", name: "Bashkir", nativeName: "башҡорт теле", flag: "🏳️" },
  { code: "eu", name: "Basque", nativeName: "Euskara", flag: "🇪🇸" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская", flag: "🇧🇾" },
  { code: "bi", name: "Bislama", nativeName: "Bislama", flag: "🇻🇺" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski", flag: "🇧🇦" },
  { code: "br", name: "Breton", nativeName: "Brezhoneg", flag: "🇫🇷" },
  { code: "bg", name: "Bulgarian", nativeName: "български", flag: "🇧🇬" },
  { code: "my", name: "Burmese", nativeName: "ဗမာစာ", flag: "🇲🇲" },
  { code: "ca", name: "Catalan", nativeName: "Català", flag: "🇪🇸" },
  { code: "ch", name: "Chamorro", nativeName: "Chamoru", flag: "🇬🇺" },
  { code: "ny", name: "Chichewa", nativeName: "Chi-Chewa", flag: "🇲🇼" },
  { code: "co", name: "Corsican", nativeName: "Corsu", flag: "🇫🇷" },
  { code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ", flag: "🏳️" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷" },
  { code: "dv", name: "Divehi", nativeName: "ދިވެހި", flag: "🇲🇻" },
  { code: "dz", name: "Dzongkha", nativeName: "རྫོང་ཁ", flag: "🇧🇹" },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto", flag: "🏳️" },
  { code: "et", name: "Estonian", nativeName: "Eesti", flag: "🇪🇪" },
  { code: "ee", name: "Ewe", nativeName: "Eʋegbe", flag: "🇬🇭" },
  { code: "fo", name: "Faroese", nativeName: "Føroyskt", flag: "🇫🇴" },
  { code: "fj", name: "Fijian", nativeName: "Vosa Vakaviti", flag: "🇫🇯" },
  { code: "ff", name: "Fula", nativeName: "Fulfulde", flag: "🏳️" },
  { code: "gd", name: "Gaelic", nativeName: "Gàidhlig", flag: "🏴" },
  { code: "gl", name: "Galician", nativeName: "Galego", flag: "🇪🇸" },
  { code: "ka", name: "Georgian", nativeName: "ქართული", flag: "🇬🇪" },
  { code: "gn", name: "Guarani", nativeName: "Avañe'ẽ", flag: "🇵🇾" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen", flag: "🇭🇹" },
  { code: "ha", name: "Hausa", nativeName: "هَوُسَ", flag: "🇳🇬" },
  { code: "ho", name: "Hiri Motu", nativeName: "Hiri Motu", flag: "🇵🇬" },
  { code: "ig", name: "Igbo", nativeName: "Asụsụ Igbo", flag: "🇳🇬" },
  { code: "io", name: "Ido", nativeName: "Ido", flag: "🏳️" },
  { code: "ia", name: "Interlingua", nativeName: "Interlingua", flag: "🏳️" },
  { code: "ie", name: "Interlingue", nativeName: "Interlingue", flag: "🏳️" },
  { code: "iu", name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ", flag: "🇨🇦" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda", flag: "🇷🇼" },
];

// const tags = [
//   { option: "mathematics" },
//   { option: "physics" },
//   { option: "chemistry" },
//   { option: "biology" },
//   { option: "history" },
//   { option: "literature" },
//   { option: "computer science" },
//   { option: "jobs" },
//   { option: "jobsearch" },
//   { option: "education" },
//   { option: "business" },
//   { option: "success" },
//   { option: "hiring" },
//   { option: "careergoals" },
//   { option: "work" },
//   { option: "motivation" },
//   { option: "recruitment" },
//   { option: "employment" },
//   { option: "careers" },
//   { option: "careerdevelopment" },
//   { option: "resume" },
//   { option: "college" },
//   { option: "goals" },
//   { option: "students" },
//   { option: "training" },
//   { option: "careeradvice" },
//   { option: "interview" },
//   { option: "nowhiring" },
//   { option: "careercoach" },
//   { option: "entrepreneur" },
//   { option: "leadership" },
//   { option: "jobseekers" },
//   { option: "student" },
//   { option: "recruiting" },
//   { option: "teaching" },
//   { option: "learning" },
//   { option: "edtech" },
//   { option: "career" },
//   { option: "guide" },
//   { option: "self-improvement" },
//   { option: "courses" },
//   { option: "study" },
//   { option: "studyabroad" },
//   { option: "studyonline" },
//   { option: "harvard" },
//   { option: "university" },
//   { option: "highschool" },
// ];

const tags = [
  { option: "career guidance" },
  { option: "study abroad" },
  { option: "job search" },
  { option: "resume tips" },
  { option: "interview preparation" },
  { option: "college admissions" },
  { option: "university applications" },
  { option: "scholarships" },
  { option: "internships" },
  { option: "apprenticeships" },
  { option: "work experience" },
  { option: "virtual internships" },
  { option: "simulations" },
  { option: "entry-level jobs" },
  { option: "positive mindset" },
  { option: "job market trends" },
  { option: "graduate jobs" },
  { option: "career coaching" },
  { option: "career planning" },
  { option: "CV writing" },
  { option: "cover letter tips" },
  { option: "soft skills" },
  { option: "hard skills" },
  { option: "technical skills" },
  { option: "networking tips" },
  { option: "job applications" },
  { option: "career assessment" },
  { option: "self-discovery" },
  { option: "strengths" },
  { option: "career success" },
  { option: "job readiness" },
  { option: "industry insights" },
  { option: "career development" },
  { option: "job interviews" },
  { option: "salary negotiation" },
  { option: "workplace etiquette" },
  { option: "professional skills" },
  { option: "time management" },
  { option: "communication skills" },
  { option: "leadership skills" },
  { option: "problem-solving skills" },
  { option: "teamwork skills" },
  { option: "critical thinking" },
  { option: "personal branding" },
  { option: "LinkedIn tips" },
  { option: "freelancing" },
  { option: "entrepreneurship" },
  { option: "a day in the life of" },
  { option: "gig economy" },
  { option: "future careers" },
  { option: "remote work opportunities" },
  { option: "internship opportunities" },
  { option: "volunteering" },
  { option: "mentorship" },
  { option: "career fairs" },
  { option: "graduate programs" },
  { option: "vocational training" },
  { option: "trade schools" },
  { option: "higher education" },
  { option: "college life" },
  { option: "university life" },
  { option: "career growth" },
  { option: "career transitions" },
  { option: "work-life balance" },
  { option: "mental health at work" },
  { option: "career motivation" },
  { option: "financial planning for students" },
  { option: "student debt" },
  { option: "budgeting" },
  { option: "career goals" },
  { option: "personal development" },
  { option: "professional development" },
  { option: "job shadowing" },
  { option: "career workshops" },
  { option: "skill development" },
  { option: "certifications" },
  { option: "online courses" },
  { option: "Micro credentials" },
  { option: "AI" },
  { option: "STEM careers" },
  { option: "creative careers" },
  { option: "business careers" },
  { option: "finance careers" },
  { option: "healthcare careers" },
  { option: "technology careers" },
  { option: "arts careers" },
  { option: "humanities careers" },
  { option: "engineering careers" },
  { option: "science careers" },
  { option: "environmental careers" },
  { option: "education careers" },
  { option: "government jobs" },
  { option: "nonprofit careers" },
  { option: "law careers" },
  { option: "media and journalism careers" },
  { option: "marketing careers" },
  { option: "sports careers" },
  { option: "fashion careers" },
  { option: "hospitality careers" },
  { option: "aviation careers" },
  { option: "transportation careers" },
  { option: "real estate careers" },
  { option: "customer service jobs" },
  { option: "retail jobs" },
  { option: "hospitality jobs" },
  { option: "summer jobs" },
  { option: "part-time jobs" },
  { option: "graduate training" },
  { option: "internship application tips" },
  { option: "UK" },
  { option: "USA" },
  { option: "Canada" },
  { option: "Australia" },
  { option: "UAE" },
  { option: "Asia" },
  { option: "India" },
  { option: "China" },
  { option: "Middle East" },
  { option: "Europe" },
];

export { categories, languages, tags };
